package com.arpitbandil.sportsapp.generators

import com.arpitbandil.sportsapp.modal.Player
import com.arpitbandil.sportsapp.modal.Team
import com.murgupluoglu.flagkit.FlagKit
import kotlin.random.Random

val teamNames = listOf(
    "Conquerors",
    "Innovators",
    "Allies",
    "Bandits",
    "Brainiacs",
    "Chosen Ones",
    "Desk champions",
    "Firefly Squad",
    "Incognito mode",
    "Performers",
    "Power Players",
    "The Deciders",
    "The Wicked crew",
    "Toon Squad",
    "Untouchables",
    "Virtuosos",
    "Wizards",
    "Wolf Pack",
    "Your Worst Nightmare"
)

val teamIcons = listOf(
    "https://static.vecteezy.com/system/resources/thumbnails/010/884/730/small_2x/owl-head-mascot-team-logo-png.png",
    "https://i.pinimg.com/originals/65/07/b0/6507b06cceca9107713f76c779c814d9.png",
    "https://static.vecteezy.com/system/resources/thumbnails/016/467/720/small/tiger-logo-esport-team-png.png",
    "https://seeklogo.com/images/M/mexico-national-football-team-logo-DD4918797B-seeklogo.com.png",
    "https://freepngimg.com/thumb/team/91409-gray-head-sports-wolf-team-logo-sport-thumb.png",
    "https://seeklogo.com/images/P/portugal-national-football-team-logo-745E6D1B4D-seeklogo.com.png",
    "https://99designs-blog.imgix.net/blog/wp-content/uploads/2020/07/1200px-Detroit_Red_Wings_logo.svg.png",
    "https://seeklogo.com/images/N/netherlands-football-team-logo-99AD54AC2D-seeklogo.com.png",
    "https://a.espncdn.com/i/teamlogos/nfl/500/ten.png",
    "https://companieslogo.com/img/orig/2020.HK-97bd150d.png",
    "https://brandlogos.net/wp-content/uploads/2014/12/tampa_bay_buccaneers-logo_brandlogos.net_mctz4.png",
    "https://s.yimg.com/cv/apiv2/default/nfl/20190724/500x500/2019_PHI.png"
)

val gameNames = listOf(
    "Fifa",
    "Dota 2",
    "Overwatch",
    "StarCraft",
    "COD",
    "Rocket League",
    "SSB",
    "Valorant",
    "Battlefy",
    "Championship",
    "Cobx Masters",
    "Coupe",
    "World Cup",
    "Fortnite",
    "Free Fire",
    "Game",
    "Halo series",
    "IAAF",
    "Intel",
    "Nba 2k"
)

val playerRoles = listOf(
    "Wicket Keeper",
    "First Slip",
    "Second slip",
    "Third Slip",
    "Fly Slip",
    "Long Stop",
    "Third man",
    "Gully",
    "Deep Gully",
    "Silly Point",
    "Point",
    "Deep Point",
    "Cover Sweeper",
    "Cover Point",
    "Extra Cover",
    "Deep Cover",
    "Silly Mid",
    "Mid Off",
    "Long Off",
    "Straight Hit",
    "Silly Mid On",
    "Mid On",
    "Long On",
    "Short Leg",
    "Short Wicket",
    "Mid Wicket",
    "Mid Wicket",
    "Sweeper",
    "Support",
    "Short",
    "Square Leg",
    "Deep",
    "Leg Gully",
    "Long Leg",
    "Leg Slip",
    "Fine Leg",
    "Deep Leg"
)

val flagCodes = FlagKit.getAllAvailableCodes()

val playerFirstNames = listOf(
    "James",
    "John",
    "Robert",
    "Michael",
    "William",
    "David",
    "Richard",
    "Charles",
    "Joseph",
    "Thomas",
    "Christopher",
    "Daniel",
    "Paul",
    "Mark",
    "Donald",
    "George",
    "Kenneth",
    "Steven",
    "Edward",
    "Brian",
    "Ronald",
    "Anthony",
    "Kevin",
    "Jason",
    "Matthew",
    "Gary",
    "Timothy",
    "Jose",
    "Larry",
    "Jeffrey",
    "Frank",
    "Scott",
    "Eric",
    "Stephen",
    "Andrew",
    "Raymond",
    "Gregory",
    "Joshua",
    "Jerry",
    "Dennis",
    "Walter",
    "Patrick",
    "Peter",
    "Harold",
    "Douglas",
    "Henry",
    "Carl",
    "Arthur",
    "Ryan",
    "Roger",
    "Joe",
    "Juan",
    "Jack",
    "Albert",
    "Jonathan",
    "Justin",
    "Terry",
    "Gerald",
    "Keith",
    "Samuel",
    "Willie",
    "Ralph",
    "Lawrence",
    "Nicholas",
    "Roy",
    "Benjamin",
    "Bruce",
    "Brandon",
    "Adam",
    "Harry",
    "Fred",
    "Wayne",
    "Billy",
    "Steve",
    "Louis",
    "Jeremy",
    "Aaron",
    "Randy",
    "Howard",
    "Eugene",
    "Carlos",
    "Russell",
    "Bobby",
    "Victor",
    "Martin",
    "Ernest",
    "Phillip",
    "Todd",
    "Jesse",
    "Craig",
    "Alan",
    "Shawn",
    "Clarence",
    "Sean",
    "Philip",
    "Chris",
    "Johnny",
    "Earl",
    "Jimmy",
    "Antonio",
    "Danny",
    "Bryan",
    "Tony",
    "Luis",
    "Mike",
    "Stanley",
    "Leonard",
    "Nathan",
    "Dale",
    "Manuel",
    "Rodney",
    "Curtis",
    "Norman",
    "Allen",
    "Marvin",
    "Vincent",
    "Glenn",
    "Jeffery",
    "Travis",
    "Jeff",
    "Chad",
    "Jacob",
    "Lee",
    "Melvin",
    "Alfred",
    "Kyle",
    "Francis",
    "Bradley",
    "Jesus",
    "Herbert",
    "Frederick",
    "Ray",
    "Joel",
    "Edwin",
    "Don",
    "Eddie",
    "Ricky",
    "Troy",
    "Randall",
    "Barry",
    "Alexander",
    "Bernard",
    "Mario",
    "Leroy",
    "Francisco",
    "Marcus",
    "Micheal",
    "Theodore",
    "Clifford",
    "Miguel",
    "Oscar",
    "Jay",
    "Jim",
    "Tom",
    "Calvin",
    "Alex",
    "Jon",
    "Ronnie",
    "Bill",
    "Lloyd",
    "Tommy",
    "Leon",
    "Derek",
    "Warren",
    "Darrell",
    "Jerome",
    "Floyd",
    "Leo",
    "Alvin",
    "Tim",
    "Wesley",
    "Gordon",
    "Dean",
    "Greg",
    "Jorge",
    "Dustin",
    "Pedro",
    "Derrick",
    "Dan",
    "Lewis",
    "Zachary",
    "Corey",
    "Herman",
    "Maurice",
    "Vernon",
    "Roberto",
    "Clyde",
    "Glen",
    "Hector",
    "Shane",
    "Ricardo",
    "Sam",
    "Rick",
    "Lester",
    "Brent",
    "Ramon",
    "Charlie",
    "Tyler",
    "Gilbert"
)

val playerLastNames = listOf(
    "Gene",
    "Marc",
    "Reginald",
    "Ruben",
    "Brett",
    "Angel",
    "Nathaniel",
    "Rafael",
    "Leslie",
    "Edgar",
    "Milton",
    "Raul",
    "Ben",
    "Chester",
    "Cecil",
    "Duane",
    "Franklin",
    "Andre",
    "Elmer",
    "Brad",
    "Gabriel",
    "Ron",
    "Mitchell",
    "Roland",
    "Arnold",
    "Harvey",
    "Jared",
    "Adrian",
    "Karl",
    "Cory",
    "Claude",
    "Erik",
    "Darryl",
    "Jamie",
    "Neil",
    "Jessie",
    "Christian",
    "Javier",
    "Fernando",
    "Clinton",
    "Ted",
    "Mathew",
    "Tyrone",
    "Darren",
    "Lonnie",
    "Lance",
    "Cody",
    "Julio",
    "Kelly",
    "Kurt",
    "Allan",
    "Nelson",
    "Guy",
    "Clayton",
    "Hugh",
    "Max",
    "Dwayne",
    "Dwight",
    "Armando",
    "Felix",
    "Jimmie",
    "Everett",
    "Jordan",
    "Ian",
    "Wallace",
    "Ken",
    "Bob",
    "Jaime",
    "Casey",
    "Alfredo",
    "Alberto",
    "Dave",
    "Ivan",
    "Johnnie",
    "Sidney",
    "Byron",
    "Julian",
    "Isaac",
    "Morris",
    "Clifton",
    "Willard",
    "Daryl",
    "Ross",
    "Virgil",
    "Andy",
    "Marshall",
    "Salvador",
    "Perry",
    "Kirk",
    "Sergio",
    "Marion",
    "Tracy",
    "Seth",
    "Kent",
    "Terrance",
    "Rene",
    "Eduardo",
    "Terrence",
    "Enrique",
    "Freddie",
    "Wade"
)

val playerImages = listOf(
    "https://www.pngall.com/wp-content/uploads/5/Model-Man-Transparent.png",
    "https://www.pngall.com/wp-content/uploads/5/Model-Man.png",
    "https://www.pngall.com/wp-content/uploads/5/Model-Man-PNG.png",
    "https://www.pngall.com/wp-content/uploads/5/Cool-Model-Man.png",
    "https://www.pngall.com/wp-content/uploads/5/Model-Man-In-Suit-PNG.png",
    "https://www.pngall.com/wp-content/uploads/5/Fashion-Model-Man-Transparent.png",
    "https://www.pngall.com/wp-content/uploads/5/Model-Man-PNG-Clipart.png",
    "https://www.pngall.com/wp-content/uploads/5/Model-Man-PNG-Image-File.png",
    "https://www.pngall.com/wp-content/uploads/5/Model-Man-PNG-Image.png",
    "https://www.pngall.com/wp-content/uploads/5/Model-Man-PNG-Photo.png",
    "https://www.pngall.com/wp-content/uploads/5/Fashion-Model-Man-PNG-Picture.png",
    "https://www.pngall.com/wp-content/uploads/5/Fashion-Model-Man-PNG-Image.png",
    "https://www.pngall.com/wp-content/uploads/5/Cool-Model-Man-PNG.png",
    "https://www.pngall.com/wp-content/uploads/5/Cool-Model-Man-PNG-Free-Image.png",
    "https://www.pngall.com/wp-content/uploads/5/Cool-Model-Man-PNG-Clipart.png",
    "https://www.pngall.com/wp-content/uploads/5/Attractive-Model-Man-PNG-Image-HD.png",
    "https://www.pngall.com/wp-content/uploads/5/Model-Man-PNG-Transparent-HD-Photo.png"
)

object Generator {
    fun generateTeams(count: Int) =  arrayListOf<Team>().apply {
        repeat((1..count).count()) {
            add(
                Team(
                    teamNames.random(),
                    teamIcons.random(),
                    Random.nextInt(1, 1000),
                    "$${Random.nextInt(1, 999)}${listOf("M", "K").random()}",
                    Random.nextBoolean(),
                    Random.nextBoolean(),
                    flagCodes.random()
                )
            )
        }
    }

    fun getGames() = arrayListOf<String>().apply {
        repeat(Random.nextInt(1, 50)) { add(gameNames.random()) }
    }.toSet().toList()

    fun generatePlayers() = arrayListOf<Player>().apply {
        repeat((1..Random.nextInt(4, 20)).count()) {
            add(
                Player(
                    playerFirstNames.random().plus(" ").plus(playerLastNames.random()),
                    playerImages.random(),
                    playerRoles.random(),
                    flagCodes.random()
                )
            )
        }
    }
}
